name: generate animation

on:
  # Chạy tự động mỗi 24 giờ
  schedule:
    - cron: "0 */24 * * *"

  # Cho phép chạy thủ công workflow bất cứ lúc nào
  workflow_dispatch:

  # Chạy khi có push lên nhánh master
  push:
    branches:
    - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: billtruong003
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=orange&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39  # Light mode with orange snake
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=orange&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353 # Dark mode with orange snake
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}