name: generate animation

on:
  # Chạy tự động mỗi 24 giờ
  schedule:
    - cron: "0 */24 * * *"

  # Cho phép chạy thủ công workflow bất cứ lúc nào
  workflow_dispatch:

  # Chạy khi có push lên nhánh master
  push:
    branches:
    - master

jobs:
  generate:
    permissions:
      contents: write # Cấp quyền ghi nội dung repository
    runs-on: ubuntu-latest # Chạy trên máy chủ Ubuntu mới nhất
    timeout-minutes: 5 # Thời gian timeout tối đa cho job là 5 phút

    steps:
      # Tạo animation snake từ biểu đồ đóng góp GitHub của người dùng (github_user_name)
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3 # Sử dụng action svg-only để tạo SVG nhanh hơn
        with:
          github_user_name: billtruong003 # **Username GitHub của bạn**
          outputs: | # Danh sách các file đầu ra
            dist/github-contribution-grid-snake.svg # File SVG animation sáng
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark # File SVG animation tối (dark mode)
          github_token: ${{ secrets.GITHUB_TOKEN }} # **Thêm token để tăng rate limit và ổn định**

      # Push file github-contribution-grid-snake.svg lên nhánh output
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0 # Sử dụng action để push lên nhánh gh-pages hoặc nhánh chỉ định
        with:
          target_branch: output # Nhánh đích để push file SVG
          build_dir: dist # Thư mục chứa file SVG đã tạo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # **Cung cấp token cho action push**